### ISSUE TITLE
Cannot use Entrypoint with 1.0.7.3

### ISSUE THREAD

**Issue by FridgeRacer** [rankynbass/XIVLauncher.Core#16]
I see in the patch notes that Entrypoint is supposed to work now, so I wanted to give it a shot.

A bit of environment info, I play the game on Arch Linux with KDE Plasma 6, with a Steam service account, and have tried all available Wine versions in the "Wine" tab of XIVLauncher.
The launcher is not installed as a Steam compatibility tool.

I cannot get "Entrypoint" loading to work with any Wine version.
When I click "Login" in XIVLauncher, it signs in and closes itself as normal, but my CPU activity spikes while no game appears, just staring at my desktop.

In `htop`, I can see the game .exe and XIVLauncher are both running.
The game application eventually closes itself (ffxiv_dx11.exe), but the Wine server and XIVLauncher.Core linger, requiring a force close, though that may be because I'm auto-starting a Discord RPC bridge with the game.. (Entrypoint does not work even with that auto-start disabled)

launcher.log: https://gist.github.com/FridgeRacer/7de90bbcce5b5b81f1d665cdcdeb8aa5
dalamud.injector.log: https://gist.github.com/FridgeRacer/f002f33dafa9405463f16ff9ddb8e752
dalamud.log: https://gist.github.com/FridgeRacer/57bd4a53d7a13bc4338d5a65dc0140e2
dalamud.boot.log: https://gist.github.com/FridgeRacer/c5583c43efb970135c58cbcf3bfcbc81

**Comment by rankynbass** [comment]
Entrypoint was added in 1.0.8.1.

**Comment by user04061** [comment]
I am experiencing this issue as well on version `1.0.8.2`. What's weird is, Dalamud will work with entrypoint injection so long as there are no plugins installed. I can install plugins once the game is launched with Dalamud, but after some time it will crash and no longer launch, leading to the same results as the OP. If any plugins are installed, the game window will not open.

I am also using the Steam service with the "Wayland" patched WINE version included in the RB launcher with DXVK 2.3.1.

xivlauncher-rb 1.0.8.2 (installed via [copr](https://copr.fedorainfracloud.org/coprs/rankyn/xivlauncher/))
Fedora 40
KDE Plasma 6.0.5 (Wayland)
NVIDIA driver version 550.78

**Comment by user04061** [comment]
> Do you have early loading in Dalamud enabled?

My "Injection delay (ms)" is set to the default of 0ms if that's what you're asking. Should I increase this to something like 30ms? "Wait for plugins before game loads" is also disabled in the in-game Dalamud settings.

>For further troubleshooting you're encouraged to join the XIVLauncher Discord guild. Not fond of them either but is what it is https://discord.gg/3NMcUV5

Thanks. I thought it would be more relevant to post it here since this is my exact issue. I had not tried the unpatched version hence why I came here instead of the official XL Discord.
