### ISSUE TITLE
Entrypoint Injection not working with 1.0.8.3 (RB patch specifically)

### ISSUE THREAD

**Issue by user04061** [rankynbass/XIVLauncher.Core#18]
As mentioned in #16, Dalamud "Entrypoint Injection" does not work for me with the RB patch. I have tried the unpatched XIVLauncher.Core and Entrypoint does work, so I'm unsure of what the root cause may be.

To quote my original comment, which should've just been a standalone issue:

> I am experiencing this issue as well on version `1.0.8.2`. What's weird is, Dalamud will work with entrypoint injection so long as there are no plugins installed. I can install plugins once the game is launched with Dalamud, but after some time it will crash and no longer launch, leading to the same results as the OP. If any plugins are installed, the game window will not open.
>
> I am also using the Steam service with the "Wayland" patched WINE version included in the RB launcher with DXVK 2.3.1.

I have since updated to 1.0.8.3 and the issue persists.

[launcher.log](https://pastebin.com/6t4SxAvD)
[dalamud.log](https://pastebin.com/rFtrasMS)
[dalamud.injector.log](https://pastebin.com/KDsWDvMv)
[dalamud.boot.log](https://pastebin.com/sve61Cxk)
(I eventually killed the process since it doesn't do anything after that point.)

xivlauncher-rb 1.0.8.3 (installed via [copr](https://copr.fedorainfracloud.org/coprs/rankyn/xivlauncher/))
Fedora 40
KDE Plasma 6.0.5 (Wayland)
NVIDIA driver version 550.78

**Comment by rankynbass** [comment]
Closing as fixed, as it's been working since Dalamud was enabled for Dawntrail.
