### ISSUE TITLE
DLSS not working with wine, only with Proton

### ISSUE THREAD

**Issue by rankynbass** [rankynbass/XIVLauncher.Core#22]
DLSS currently does not work with wine + dxvk. It *does* work with Proton. Setting up this issue to help figure out why. Test builds will be posted here: https://github.com/rankynbass/XIVLauncher.Core/releases/tag/nvapi-test-1

**Comment by rovacado** [comment]
[dxvk-nvapi.log](https://github.com/user-attachments/files/16077845/dxvk-nvapi.log)
[ffxiv_dx11_d3d11.log](https://github.com/user-attachments/files/16077846/ffxiv_dx11_d3d11.log)
[ffxiv_dx11_dxgi.log](https://github.com/user-attachments/files/16077848/ffxiv_dx11_dxgi.log)
[launcher.log](https://github.com/user-attachments/files/16077849/launcher.log)
[wine.log](https://github.com/user-attachments/files/16077850/wine.log)

Logs from running test 2 on my system, which just for the record is a ryzen 7 5800x, nvidia 3070. running arch with cachyos kernel 6.9.7-1 and dkms-nvidia with modeset=1 and fbdev=1 set in modprobe. all running ontop of kwin latest stable (6.1.1 as of yesterday when the logs were generated i believe)

**Comment by rankynbass** [comment]
Could you try going to the wine tab, use the Open Wine Explorer button (run apps in prefix, not use WineD3D). Then browse to C:\windows\system32 and run nvapi64-tests.exe. Then repost the dxvk-nvapi log.

**Comment by rovacado** [comment]
[dxvk-nvapi.log from nvapi64-tests.exe](https://github.com/user-attachments/files/16090492/dxvk-nvapi.log)
[nvapi64-tests_dxgi.log from nvapi64-tests.exe](https://github.com/user-attachments/files/16090493/nvapi64-tests_dxgi.log)

[dxvk-nvapi.log](https://github.com/user-attachments/files/16090517/dxvk-nvapi.log)
[ffxiv_dx11_d3d11.log](https://github.com/user-attachments/files/16090521/ffxiv_dx11_d3d11.log)
[ffxiv_dx11_dxgi.log](https://github.com/user-attachments/files/16090522/ffxiv_dx11_dxgi.log)
[wine.log](https://github.com/user-attachments/files/16090523/wine.log)

here are the newest logs from running the binary from the tarball. I'm seeing a lot of complaints about not finding displays properly. currently I'm running 2 monitors stacked, a 2560x1080@60 on top and 3440x1440@160 on the bottom. I'm a dabbler at best when it comes to understanding anything to do with graphics APIs so if you think that could be throwing it off and want to me test with a single monitor setup just let me know, though fwiw using your forked launcher with proton works without issue.

**Comment by drakon64** [comment]
What worked for me on NixOS with XIVLauncher-RB 1.1.0.9:
- Copy `nvapi64.dll` from DXVK-NVAPI to `.xlcore/wineprefix/drive_c/windows/system32/nvapi64.dll`
- Copy `nvapi.dll` from DXVK-NVAPI to `.xlcore/wineprefix/drive_c/windows/syswow64/nvapi.dll`
- Copy `nvngx.dll` and `_nvngx.dll` from the NVIDIA driver to `.xlcore/ffxiv/game/`
  - This should be under `/usr/lib/nvidia/wine/`, on NixOS the paths are totally different so I can't be sure
- Add the following to `WINEDLLOVERRIDES`:
  - `nvapi,nvapi64,nvngx,_nvngx=n,b`

**Comment by Charlignon** [comment]
Ubuntu 23.10 on X11, Nvidia RTX 4060, and XIVLauncher Core 1.1.0.0
The two `nvapi*.dll` in `drive_c/...` are already symlink to my DXVK-NVAPI install (6.4, which is not up to date, but not sure it has any effect)
Same for dll in `.xlcore/ffxiv/game/`, they're pointing to my driver.
It came out like that out of the box, but even though I didn't touch any file, it should be functionally identical.

I added the wine arguments, but even with all that, the menu item stay grayed out

**Comment by drakon64** [comment]
> Ubuntu 23.10 on X11, Nvidia RTX 4060, and XIVLauncher Core 1.1.0.0
> 
> The two `nvapi*.dll` in `drive_c/...` are already symlink to my DXVK-NVAPI install (6.4, which is not up to date, but not sure it has any effect)
> 
> Same for dll in `.xlcore/ffxiv/game/`, they're pointing to my driver.
> 
> It came out like that out of the box, but even though I didn't touch any file, it should be functionally identical.
> 
> 
> 
> I added the wine arguments, but even with all that, the menu item stay grayed out

You might also need DXVK 2.x

**Comment by rankynbass** [comment]
Wine DLSS added in [rb-v1.1.0.10](https://github.com/rankynbass/XIVLauncher.Core/releases/tag/rb-v1.1.0.10). Requires valve wine 8+ or wine 9.0+ and DXVK 2.0+.
