### ISSUE TITLE
XL_PATH Not Being Honored

### ISSUE THREAD

**Issue by trowgundam** [rankynbass/XIVLauncher.Core#23]
I am using the AUR package on Arch. I just upgraded from 1.1.0.1 to 1.1.0.3. After this my XL_PATH Environment Variable is no longer honored. I was able to go into the settings and change the locations back to the old path, but I did lose all my launcher settings and needed to redownload WINE and DXVK. My game settings and files all seem to be fine though.

**Comment by rankynbass** [comment]
Yeah, my mistake. Accidentally deleted it when doing the merge from 1.1.0.1 to 1.1.0.2. I've added it back in with 1.1.0.4.
