### ISSUE TITLE
Could not Obtain Process Handle  due to failure to download dxvk-nvapi

### ISSUE THREAD

**Issue by dragynbane222** [rankynbass/XIVLauncher.Core#28]
For at least 2 releases XIVLauncher has been unable to download dxvk-nvapi properly, a workaround has been manually downloading the appropriate version and placing the unzipped files in the proper place.

The launcher just tries to download and immediately fails throwing an exception in the logs. I'm attaching the launcher logs here.
[launcher.log](https://github.com/user-attachments/files/17536402/launcher.log)

**Comment by rankynbass** [comment]
Fixed with [rb-v1.1.0.18](https://github.com/rankynbass/XIVLauncher.Core/releases/tag/rb-v1.1.0.18)
